### Variables
@baseUrl = http://localhost:5117

### Get Users
GET {{baseUrl}}/users/
Accept: application/json

### Create User
POST {{baseUrl}}/users/
Content-Type: application/json

{
  "name": "John Doe",
  "email": "jon@doe.com",
  "roleId": 1,
  "active": true
}
###
